### ISSUE TITLE
can not install add-on

### ISSUE THREAD

**Issue by hoeffyF** [ChristopheHD/HA_enoceanmqtt-addon#11]
HA: 2024.12.2

Hi,
I have problems to install the add-on.
Do you have an idea?

Thanks a lot
hoeffyF

LOG:
Failed to to call /store/repositories - Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/aseracorp/HA_enoceanmqtt-addon /data/addons/git/9a67bcf7 stderr: 'Cloning into '/data/addons/git/9a67bcf7'... fatal: could not read Username for 'https://github.com': No such device or address '

and

Failed to to call /addons/f93730fa_ha_enoceanmqtt_aseracorp/install - The command '/bin/ash -o pipefail -c apk add --no-cache python3 py3-pip git && python3 -m venv /app/venv && . /app/venv/bin/activate && python3 -m pip install --upgrade pip && pip3 install -r requirements.txt && pip3 install git+https://github.com/aseracorp/enocean.git && git clone -b master --single-branch --depth 1 https://github.com/embyt/enocean-mqtt.git && cd enocean-mqtt && python3 setup.py develop && cd .. && echo "Installing from repository head" && git clone -b develop --single-branch --depth 1 https://github.com/aseracorp/HA_enoceanmqtt.git ; cp -rf ./HA_enoceanmqtt/enoceanmqtt enocean-mqtt && rm -rf ./HA_enoceanmqtt' returned a non-zero code: 1

**Comment by ChristopheHD** [comment]
Hello,
First log indicate you have not entered the correct addon-repository address. Can you indicate me where you find it or what you did to trigger this log ?

The second log indicates a failure during installation but is not developped enough to indicate at which point. I made some tests today with HA 2024.12.3 and addon 0.1.32 and 0.1.33 without any issue. Can you retry with the latest version of addon ?

**Comment by ChristopheHD** [comment]
> Hi, I used the light blue add repository button „from“ github.

Can you indicate on which Github page you found that blue button ? Because I reviewed all blue buttons and they shall not create that log.
I don't understand how you manage to launch the addon installation process if you've got this log when installing the repository.

> With 0.1.33 it shows:
> 
> The command '/bin/ash -o pipefail -c apk add --no-cache python3 py3-pip git && python3 -m venv /app/venv && . /app/venv/bin/activate && python3 -m pip install --upgrade pip && pip3 install -r requirements.txt && pip3 install git+https://github.com/aseracorp/enocean.git && git clone -b master --single-branch --depth 1 https://github.com/embyt/enocean-mqtt.git && cd enocean-mqtt && python3 setup.py develop && cd .. && echo "Installing from repository head" && git clone -b develop --single-branch --depth 1 https://github.com/aseracorp/HA_enoceanmqtt.git ; cp -rf ./HA_enoceanmqtt/enoceanmqtt enocean-mqtt && rm -rf ./HA_enoceanmqtt' returned a non-zero code: 1
> 
> Do I need to uninstall the old version from mak-gitdev first?
> 
> Thanks in advance hoeffyF

You do not need to uninstall the old version mak-gitdev.
Have you got any Supervisor log ? To see Supervisor log, go in HA -> Settings -> Systems -> Logs -> Select Supervisor on the top right

**Comment by hoeffyF** [comment]
Hi,
I used this one:
https://github.com/ChristopheHD/HA_enoceanmqtt-addon
Setup
Installation
ADD ADD-ON REPOSITORY TO MY(HA)
then
HA -> Add-ons
EnOcean MQTT
Install

The version from mak-gitdev is running for month on V. 0.1.28-2

**Comment by ChristopheHD** [comment]
The blue button is correct, so let's set aside this first issue.
For the installation issue, I don't know what happens. Have you got any Supervisor log as indicated in my previous message ?

**Comment by ChristopheHD** [comment]
Perfect ! The interesting log is this one:
`fatal: unable to access 'https://github.com/aseracorp/enocean.git/': Could not resolve host: [github.com](http://github.com/)`

This is linked to the first issue you mention in your first message : it seems your Home Assistant have trouble to access GitHub. It's a DNS issue, can you try changing your DNS and try again ?

**Comment by hoeffyF** [comment]
crazy
You are right. Thank you and sorry.
I am wondering because of download is possible but clone not.
Strange thing.

And thank you for your work here at the project.

**Comment by djkroko** [comment]
> crazy You are right. Thank you and sorry. I am wondering because of download is possible but clone not. Strange thing.
> 
> And thank you for your work here at the project.

How did you solved your Problem?

I also have the unable to access error but with a different page:
fatal: unable to access 'https://github.com/embyt/enocean-mqtt.git/': Could not resolve host: github.com

But when i try to ping github from HA Terminal there is no problem.
