### ISSUE TITLE
TCP configuration not available

### ISSUE THREAD

**Issue by ChristopheHD** [ChristopheHD/HA_enoceanmqtt-addon#7]
See https://github.com/mak-gitdev/HA_enoceanmqtt/issues/158#issuecomment-2508920889

**Comment by madejackson** [comment]
Looking at the code I'd say you just type `tcp:address` instead of the serial port (like `/dev/ttyUSB0`) into `enocean_port =`

**Comment by TTr0n** [comment]
Let me know, if you want me to test.
However, I will need a little help setting up the configuration ;-)

**Comment by ChristopheHD** [comment]
Tests are in progress, I have some issue with updating the configuration schema (HA seems not to handle dynamically change in the configuration schema). I keep you posted.
Can someone confirm to me that the valid configuration for TCP is tcp:<ip_address>:<port> ?

**Comment by TTr0n** [comment]
Any news ?

**Comment by ChristopheHD** [comment]
Release 0.1.33 shoud work with TCP configuration, can you test ?

**Comment by ChristopheHD** [comment]
Like that:
```
[fenetre_chambre_3]
address 		= 0x01A6F94F
rorg    		= 0xf6
func    		= 0x10
type    		= 0x00
```

**Comment by TTr0n** [comment]
Ok, done ... no more unknown sensor, but no message from known sensor, ist it ok ?
Where do i find the sensors? There isnt anything .. !?

**Comment by ChristopheHD** [comment]
It's normal behavior to see no logs of known sensor.
You can find the sensor in the list of devices of Home Assistant.
